name: Build

on:
  push:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build
        run: mvn clean install --batch-mode --threads 8C --no-transfer-progress -DskipTests --no-transfer-progress

      - name: Unit test
        run: mvn test --batch-mode --threads 8C --no-transfer-progress

      - name: Integration test
        run: mvn failsafe:integration-test failsafe:verify --batch-mode --threads 8C --no-transfer-progress

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: /language:java

      - name: Update dependency graph
        if: github.ref == 'refs/heads/main'
        uses: advanced-security/maven-dependency-submission-action@v4.0.0
